- name: "Dr. Randall Evans"
  description: "Northwest Pet Clinic\nTwo locations:\n6745 N La Canada Dr,\n252 W Ina Rd,"
  website: "http://www.northwestpetclinic.com"
  phone: "520-742-4148"
  map: ""
- name: "Dr. ShanAnne Edwards"
  description: "Arizona Small Animal Clinic\n10 E 31st St,\nTucson, AZ 85213"
  website: "http://www.azsmallanimalclinic.com"
  phone: "520-622-6231"
  map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3376.2536208344472!2d-110.97006088483256!3d32.19739598115088!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86d67093f23a2eab%3A0x83934012f252abb7!2sArizona+Small+Animal+Clinic!5e0!3m2!1sen!2sus!4v1444445646479"
- name: "Dr. Jody Moffett"
  description: "Sierra Animal Hospital\n900 S Hwy 92,\nSierra Vista, AZ 85635"
  website: "http://www.sierraanimalhospital.com"
  phone: "520-458-8656"
  map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3400.211236104854!2d-110.25961468484876!3d31.545816981361178!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86d7293d09df785b%3A0x7d744abf030e17b8!2sSierra+Animal+Hospital!5e0!3m2!1sen!2sus!4v1444445583982"
- name: "Dr. Michael Samuels"
  description: "Central Animal Hospital\n4020 E Speedway Blvd,\nTucson, AZ 85712"
  website: "http://www.centralah.com"
  phone: "520-323-9912"
  map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3374.8268461598313!2d-110.90908878483167!3d32.23582848113872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86d671ca0fbabf3d%3A0x14f689faf4f772d!2sCentral+Animal+Hospital!5e0!3m2!1sen!2sus!4v1444445508325"
